import Head from "next/head";
import { subscribe } from "@/lib/helper";
import axios from "axios";
import { url } from "@/lib/constants";

export default function Home() {
  function check() {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register("/service-worker.js");
      axios.post(`${url}/log`, {
        message: "This browser supports serviceWorker.",
        userAgent: window.navigator.userAgent,
        isSecureContext: window.isSecureContext,
      });
    } else {
      // https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#examples
      // The current browser doesn't support service workers.
      // Perhaps it is too old or we are not in a Secure Context(e.g. localhost, https).
      axios.post(`${url}/log`, {
        message: "This browser doesn't support serviceWorker.",
        userAgent: window.navigator.userAgent,
        isSecureContext: window.isSecureContext,
      });
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={subscribe}>subscribe</button>
      <button onClick={check}>check</button>
    </>
  );
}
